[package]
name = "rs8080"
version = "0.1.0"
authors = ["michele <michele.damico@gmail.com>"]

[profile.release]
debug = true

[workspace]
members = ["space_invaders"]


[dependencies]
log = "*"

[dev-dependencies]
rstest = "0.2"